# Generated by Django 3.2.10 on 2022-02-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
