# Generated by Django 3.2.10 on 2022-02-08 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickles', '0002_alter_pickle_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pickle',
        ),
    ]
